from pathlib import Path

path = Path('.agent/ORCHESTRATOR_ECOSYSTEM_ROADMAP.yaml')
text = path.read_text()

fact_anchor = '''  - human_required_remains_non_automatable_and_check_names_runner_labels_emulation_compile_success_and_prose_are_not_hardware_evidence\n'''
fact_insert = fact_anchor + '''  - ORCH6b_PR_52_merged_at_main_c73ee0628419fb693e6d2169f9778ad7004e2ef8_with_exact_head_72612269b3de6054093cd366cdd41681fcfda12c_green_CI\n  - hardware_missing_evidence_defer_is_typed_and_only_missing_evidence_is_dispatch_eligible\n  - hardware_dispatch_uses_Orchestrator_owned_strict_configuration_direct_shell_free_argv_and_exact_binding_token\n  - exact_successful_hardware_dispatch_is_idempotent_and_never_counts_as_hardware_evidence\n'''
if text.count(fact_anchor) != 1:
    raise SystemExit('verified facts anchor mismatch')
text = text.replace(fact_anchor, fact_insert, 1)

old = '''  - id: ORCH6\n    name: CI capability and hardware scheduling\n    status: active_priority\n    next_slice: ORCH6b_capability_aware_hardware_evidence_discovery_and_dispatch\n    completed_slices:\n      - id: ORCH6a\n        name: Authoritative hardware evidence contract with pinned attestations\n        status: complete\n        completion_evidence:\n          - issue_49_defined_authoritative_hardware_evidence_contract\n          - PR_50_merged_to_main_as_b1bcaed3eb94c88338de359aa946210730e32019\n          - exact_head_e666c1be1b9a564ad7cbe14c7a98bb46e2c13b80_ci_174_and_contributor_attribution_41_completed_success_before_merge\n          - workspace_Rust_tests_149_of_149_and_root_portable_validation_tests_10_of_10\n          - merge_evidence_policy_v1_behavior_preserved_and_v2_hardware_requirement_id_strictly_scoped\n          - local_Orchestrator_owned_signer_workflow_and_digest_trust_root_is_not_repository_policy\n          - exact_manifest_repository_PR_head_base_policy_requirement_device_and_time_binding\n          - gh_attestation_verify_pins_repository_signer_workflow_signer_digest_source_digest_and_SLSA_v1_predicate_type\n          - missing_trust_evidence_or_verifier_defers_without_success_and_malformed_or_identity_mismatched_state_fails_closed\n          - hardware_gate_revalidated_before_remote_mutations_and_immediately_before_final_merge\n          - no_review_threads_open_at_merge_and_no_staging_artifacts_in_product_branch\n    goals:\n'''
new = '''  - id: ORCH6\n    name: CI capability and hardware scheduling\n    status: active_priority\n    next_slice: ORCH6c_authoritative_remote_evidence_discovery_and_ingestion\n    completed_slices:\n      - id: ORCH6a\n        name: Authoritative hardware evidence contract with pinned attestations\n        status: complete\n        completion_evidence:\n          - issue_49_defined_authoritative_hardware_evidence_contract\n          - PR_50_merged_to_main_as_b1bcaed3eb94c88338de359aa946210730e32019\n          - exact_head_e666c1be1b9a564ad7cbe14c7a98bb46e2c13b80_ci_174_and_contributor_attribution_41_completed_success_before_merge\n          - workspace_Rust_tests_149_of_149_and_root_portable_validation_tests_10_of_10\n          - merge_evidence_policy_v1_behavior_preserved_and_v2_hardware_requirement_id_strictly_scoped\n          - local_Orchestrator_owned_signer_workflow_and_digest_trust_root_is_not_repository_policy\n          - exact_manifest_repository_PR_head_base_policy_requirement_device_and_time_binding\n          - gh_attestation_verify_pins_repository_signer_workflow_signer_digest_source_digest_and_SLSA_v1_predicate_type\n          - missing_trust_evidence_or_verifier_defers_without_success_and_malformed_or_identity_mismatched_state_fails_closed\n          - hardware_gate_revalidated_before_remote_mutations_and_immediately_before_final_merge\n          - no_review_threads_open_at_merge_and_no_staging_artifacts_in_product_branch\n      - id: ORCH6b\n        name: Trusted capability dispatch for missing hardware evidence\n        status: complete\n        completion_evidence:\n          - issue_51_defined_trusted_idempotent_hardware_dispatch_scope\n          - PR_52_merged_to_main_as_c73ee0628419fb693e6d2169f9778ad7004e2ef8\n          - exact_head_72612269b3de6054093cd366cdd41681fcfda12c_ci_176_and_contributor_attribution_43_completed_success_before_merge\n          - workspace_Rust_tests_158_of_158_and_root_portable_validation_sandbox_integration_completed_success\n          - typed_missing_trust_missing_evidence_verifier_unavailable_and_attestation_not_verified_reasons\n          - only_missing_evidence_can_dispatch_and_dispatch_success_still_returns_deferred\n          - Orchestrator_owned_dispatch_repository_workflow_ref_configuration_is_strict_and_non_repository_controlled\n          - deterministic_exact_repository_PR_head_base_policy_requirement_binding_token\n          - durable_dispatching_and_dispatched_state_prevents_duplicate_exact_remote_dispatch\n          - state_directory_components_are_created_fail_closed_without_following_symlink_escapes\n          - no_review_threads_or_reviews_blocked_merge_and_no_staging_artifacts_entered_product_branch\n    goals:\n'''
if text.count(old) != 1:
    raise SystemExit('ORCH6 section anchor mismatch')
text = text.replace(old, new, 1)
path.write_text(text)
print('ORCH6b roadmap patch applied')
